networks:
  default:
    name: np-core-net
services:
  np-offloading-service:
    build: .
    image: np-offloading-service
    container_name: np-offloading-service
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - .env
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      start_period: 60s
      interval: 5s
      timeout: 20s
      retries: 10
